-- Editorial colorscheme loader for Neovim
-- Generated by codegen.rb

vim.cmd('hi clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end
vim.o.termguicolors = true
vim.g.colors_name = 'editorial'

local colors = {

  bg = "#292826",

  surface = "#383634",

  border = "#474543",

  fg = "#b8b2aa",

  text = "#e0dcd5",

  muted = "#787368",

  accent = "#e08856",

  alert = "#f0c040",

  success = "#90a080",

  error = "#d06560",

  info = "#90a8c0",

}

local highlights = {
  -- Editor highlights
  Normal = { fg = colors.text, bg = colors.bg },
  NormalFloat = { fg = colors.text, bg = colors.surface },
  LineNr = { fg = colors.muted },
  CursorLine = { bg = colors.surface },
  CursorLineNr = { fg = colors.accent, bold = true },
  Visual = { bg = colors.border },
  VertSplit = { fg = colors.border, bg = colors.bg },
  StatusLine = { fg = colors.text, bg = colors.surface },
  StatusLineNC = { fg = colors.muted, bg = colors.border },
  
  -- Syntax highlights
  Comment = { fg = colors.muted, italic = true },
  String = { fg = colors.success },
  Character = { fg = colors.success },
  Number = { fg = colors.info },
  Boolean = { fg = colors.alert },
  Float = { fg = colors.info },
  Function = { fg = colors.accent },
  Identifier = { fg = colors.fg },
  Keyword = { fg = colors.alert, bold = true },
  Statement = { fg = colors.alert },
  Conditional = { fg = colors.alert },
  Repeat = { fg = colors.alert },
  Label = { fg = colors.accent },
  Operator = { fg = colors.fg },
  Exception = { fg = colors.error },
  Type = { fg = colors.info },
  Structure = { fg = colors.info },
  Constant = { fg = colors.error },
  Special = { fg = colors.accent },
  
  -- Diagnostics
  DiagnosticError = { fg = colors.error },
  DiagnosticWarn = { fg = colors.alert },
  DiagnosticInfo = { fg = colors.info },
  DiagnosticHint = { fg = colors.success },
  
  -- Git signs
  GitSignsAdd = { fg = colors.success },
  GitSignsChange = { fg = colors.alert },
  GitSignsDelete = { fg = colors.error },
  
  -- Telescope
  TelescopeSelection = { bg = colors.surface },
  TelescopeSelectionCaret = { fg = colors.accent },
  TelescopeMultiSelection = { bg = colors.border },
  TelescopeNormal = { bg = colors.bg },
  TelescopeBorder = { fg = colors.border },
  TelescopePromptNormal = { bg = colors.surface },
  TelescopePromptBorder = { fg = colors.accent },
  TelescopeResultsNormal = { bg = colors.bg },
  TelescopeResultsBorder = { fg = colors.border },
  TelescopePreviewNormal = { bg = colors.bg },
  TelescopePreviewBorder = { fg = colors.border },
}

for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
